services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
     - ./data/db:/var/lib/postgresql/data
    container_name: db

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    container_name: backend
    depends_on:
      - db
    
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    container_name: frontend
    depends_on:
      - backend

volumes:
  pg_data:
    driver: local 